service: simulator-lambda

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 512
  timeout: 15
  stage: dev
  region: eu-west-2

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY {proxy+}
      - http: ANY /
