name: Pull request job

on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "yarn"
      - run: yarn install
      - run: yarn test
      - run: yarn int-test
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY_DEV }}
      - run: yarn build
