name: Pull request job

on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "yarn"
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - run: yarn start & wait-on http://localhost:3000
      - run: yarn test:e2e -- --spec "cypress/integration/dataPlotter.spec.js"
