name: Pull request job

on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    env:
      REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY_DEV }}
      TEST: "TEST1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "yarn"
      - name: Print name
        run: echo "Hello $TEST. $BUILD. My API_KEY is $REACT_APP_API_KEY"
        env:
          BUILD: "We are currently running the Build job"
      - run: yarn install
      - run: yarn test
      #- run: yarn int-test
      - run: yarn build
